spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/facechamp
    username: database_instance_username # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    password: database_instance_password # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    sql-script-encoding: UTF-8
    tomcat:
      validation-query: 'SELECT 1'
      test-while-idle: true
      test-on-borrow: true
  jpa:
    show-sql: false # 설정 클래스에서 false 설정함.
    generate-ddl: false
