facechamp:
  api:
    nonce:
      secret: onm1buslKKOzDfa9qZsP
spring:
  datasource:
    username: root
    password: ""
  jpa:
    generate-ddl: true
logging:
  level:
    facechamp: trace
    org.hibernate.SQL: debug
